package mapleleaf.materialdesign.engine.map;

import java.util.HashMap;

public class DeviceNameMapper {

    private static HashMap<String, String> deviceNameMap = new HashMap<>();

    static {
        // 添加设备代号与名称的映射关系
        deviceNameMap.put("sapphiren", "红米Note13 4G NFC");
        deviceNameMap.put("sapphire", "红米Note13 4G");
        deviceNameMap.put("air", "红米13R 5G / 红米13C 5G");
        deviceNameMap.put("duchamp", "红米K70E / POCO X6 Pro 5G");
        deviceNameMap.put("manet", "红米K70 Pro");
        deviceNameMap.put("vermeer", "红米K70");
        deviceNameMap.put("gale", "红米13C / POCO C65");
        deviceNameMap.put("shennong", "小米14 Pro");
        deviceNameMap.put("houji", "小米14");
        deviceNameMap.put("aristotle", "小米13T");
        deviceNameMap.put("garnet", "红米Note13 Pro 4G / POCO X6");
        deviceNameMap.put("gold", "红米Note13 5G / 13R Pro");
        deviceNameMap.put("zircon", "红米Note13 Pro 5G / Pro+ 5G");
        deviceNameMap.put("xun", "红米平板SE");
        deviceNameMap.put("babylon", "小米MIX Fold 3");
        deviceNameMap.put("corot", "红米K60 至尊版 / 小米13T Pro");
        deviceNameMap.put("yudi", "小米平板6 Max");
        deviceNameMap.put("emerald", "POCO M6 Pro 4G");
        deviceNameMap.put("sky", "红米Note12R / POCO M6 Pro 5G / 红米12 5G");
        deviceNameMap.put("fire", "红米12");
        deviceNameMap.put("pearl", "红米Note12T Pro");
        deviceNameMap.put("yuechu", "小米CIVI3");
        deviceNameMap.put("sea", "红米Note12S");
        deviceNameMap.put("ishtar", "小米13 Ultra");
        deviceNameMap.put("liuqin", "小米平板6 Pro");
        deviceNameMap.put("pipa", "小米平板6");
        deviceNameMap.put("sweet_k6a", "红米Note12 Pro 4G");
        deviceNameMap.put("topaz", "红米Note12 4G NFC");
        deviceNameMap.put("tapas", "红米Note12 4G");
        deviceNameMap.put("marble", "红米Note12 Turbo / POCO F5 5G");
        deviceNameMap.put("water", "POCO C51 / 红米A2 / A2+");
        deviceNameMap.put("earth", "红米12C / POCO C55");
        deviceNameMap.put("redwood", "红米Note12 Pro 极速版 / POCO X5 Pro 5G");
        deviceNameMap.put("rembrandt", "红米K60E");
        deviceNameMap.put("socrates", "红米K60 Pro");
        deviceNameMap.put("mondrian", "红米K60");
        deviceNameMap.put("nuwa", "小米13 Pro");
        deviceNameMap.put("fuxi", "小米13");
        deviceNameMap.put("moonstone", "POCO X5 5G");
        deviceNameMap.put("sunstone", "红米Note12 5G / 红米Note12R Pro");
        deviceNameMap.put("ruby", "红米Note12 Pro");
        deviceNameMap.put("plato", "小米12T");
        deviceNameMap.put("yunluo", "红米平板");
        deviceNameMap.put("ziyi", "小米CIVI 2 / 小米13 Lite");
        deviceNameMap.put("ice", "POCO C50 / 红米A1");
        deviceNameMap.put("rosemary_p", "POCO M5S");
        deviceNameMap.put("rock", "POCO M5 / 红米11 Prime 4G");
        deviceNameMap.put("dagu", "小米平板5 Pro 12.4");
        deviceNameMap.put("diting", "红米K50 至尊版 / 小米12T Pro");
        deviceNameMap.put("zizhan", "小米MIX Fold 2");
        deviceNameMap.put("mayfly", "小米12S");
        deviceNameMap.put("thor", "小米12S Ultra");
        deviceNameMap.put("unicorn", "小米12S Pro");
        deviceNameMap.put("daumier", "小米12 Pro 天玑版");
        deviceNameMap.put("taoyao", "小米12 Lite");
        deviceNameMap.put("frost", "POCO C40");
        deviceNameMap.put("xaga", "红米Note11T Pro / Pro+ / POCO X4 GT / Pro / 红米K50i / Pro");
        deviceNameMap.put("zijin", "小米CIVI 1S");
        deviceNameMap.put("lilac", "红米Note 10T");
        deviceNameMap.put("dandelion", "红米10A");
        deviceNameMap.put("fog", "红米10C");
        deviceNameMap.put("rubens", "红米K50");
        deviceNameMap.put("matisse", "红米K50 Pro");
        deviceNameMap.put("munch", "红米K40S / POCO F4");
        deviceNameMap.put("viva", "红米Note11 Pro");
        deviceNameMap.put("lightcm", "红米Note11R");
        deviceNameMap.put("light", "红米Note11E / POCO M4 5G / 红米10 Prime+ 5G");
        deviceNameMap.put("ingres", "红米K50 电竞版 / POCO F4 GT");
        deviceNameMap.put("spesn", "红米Note11 NFC");
        deviceNameMap.put("spes", "红米Note11");
        deviceNameMap.put("veux", "红米Note11E Pro / 红米Note11 Pro 5G");
        deviceNameMap.put("opal", "红米Note 11S 5G");
        deviceNameMap.put("fleur", "红米Note 11S / POCO M4 Pro 4G");
        deviceNameMap.put("zeus", "小米12 Pro");
        deviceNameMap.put("psyche", "小米12X");
        deviceNameMap.put("cupid", "小米12");
        deviceNameMap.put("evergreen", "POCO M4 Pro 5G");
        deviceNameMap.put("pissarro", "红米Note11 Pro / Pro+");
        deviceNameMap.put("evergo", "红米Note11 5G");
        deviceNameMap.put("selenes", "红米Note11 4G");
        deviceNameMap.put("mona", "小米CIVI");
        deviceNameMap.put("lisa", "小米11青春活力版");
        deviceNameMap.put("agate", "小米11T");
        deviceNameMap.put("vili", "小米11T Pro");
        deviceNameMap.put("selene", "红米10");
        deviceNameMap.put("odin", "小米MIX4");
        deviceNameMap.put("elish", "小米平板5 Pro (WiFi)");
        deviceNameMap.put("enuma", "小米平板5 Pro (5G)");
        deviceNameMap.put("nabu", "小米平板5");
        deviceNameMap.put("chopin", "红米Note 10 Pro (China) / POCO X3 GT");
        deviceNameMap.put("camellia", "红米Note 10 (China) / POCO M3 Pro / 红米Note 11 SE");
        deviceNameMap.put("biloba", "红米Note 8 (21年款)");
        deviceNameMap.put("ares", "红米K40 游戏增强版 / POCO F3 GT");
        deviceNameMap.put("cetus", "小米MIX Fold");
        deviceNameMap.put("renoir", "小米11 青春版");
        deviceNameMap.put("star", "小米11 Pro / Ultra");
        deviceNameMap.put("courbet", "小米11 Lite");
        deviceNameMap.put("vayu", "POCO X3 Pro");
        deviceNameMap.put("thyme", "小米10S");
        deviceNameMap.put("sweet", "红米Note 10 Pro");
        deviceNameMap.put("camellian", "红米Note 10 5G");
        deviceNameMap.put("rosemary", "红米Note 10S");
        deviceNameMap.put("mojito", "红米Note 10");
        deviceNameMap.put("haydn", "红米K40 Pro / Pro+ / 小米11i / 小米11X Pro");
        deviceNameMap.put("alioth", "红米K40 / POCO F3");
        deviceNameMap.put("venus", "小米11");
        deviceNameMap.put("cannong", "红米Note 9T 5G");
        deviceNameMap.put("gauguin", "红米Note 9 Pro 5G / 小米10T Lite");
        deviceNameMap.put("cannon", "红米Note 9 5G");
        deviceNameMap.put("lime", "红米Note 9 4G / 红米9T");
        deviceNameMap.put("citrus", "POCO M3");
        deviceNameMap.put("apollo", "红米K30S 至尊纪念版 / 小米10T / 10T Pro");
        deviceNameMap.put("angelicain", "POCO C3");
        deviceNameMap.put("shiva", "POCO M2");
        deviceNameMap.put("surya", "POCO X3 NFC");
        deviceNameMap.put("angelican", "红米9C NFC");
        deviceNameMap.put("cattail", "红米9 (India)");
        deviceNameMap.put("cas", "小米10 至尊纪念版");
        deviceNameMap.put("cezanne", "红米K30 至尊纪念版");
        deviceNameMap.put("gram", "POCO M2 Pro");
        deviceNameMap.put("dandelion", "红米9A / 9AT");
        deviceNameMap.put("angelica", "红米9C");
        deviceNameMap.put("lancelot", "红米9");
        deviceNameMap.put("toco", "小米Note10 Lite");
        deviceNameMap.put("bomb", "红米10X Pro");
        deviceNameMap.put("atom", "红米10X 5G");
        deviceNameMap.put("picasso_48m", "红米K30i 5G");
        deviceNameMap.put("merlin", "红米10X 4G / 红米Note 9");
        deviceNameMap.put("vangogh", "小米10 青春版");
        deviceNameMap.put("monet", "小米10 Lite");
        deviceNameMap.put("lmi", "红米K30 Pro / 变焦版 / POCO F2 Pro");
        deviceNameMap.put("excalibur", "红米Note 9 Pro Max");
        deviceNameMap.put("curtana", "红米Note 9S / Pro (India)");
        deviceNameMap.put("joyeuse", "红米Note9 Pro");
        deviceNameMap.put("cmi", "小米10 Pro");
        deviceNameMap.put("umi", "小米10");
        deviceNameMap.put("olivewood", "红米8A Pro / 红米8A Dual");
        deviceNameMap.put("phoenixin", "POCO X2 印度版");
        deviceNameMap.put("picasso", "红米K30 5G");
        deviceNameMap.put("phoenix", "红米K30 4G / POCO X2");
        deviceNameMap.put("willow", "红米Note 8T");
        deviceNameMap.put("tucana", "小米CC9 Pro / 小米Note 10");
        deviceNameMap.put("begoniain", "红米Note 8 Pro 印度版");
        deviceNameMap.put("dipper", "小米8");
        deviceNameMap.put("equuleus", "小米8 Pro 屏幕指纹版");
        deviceNameMap.put("sirius", "小米8 SE");
        deviceNameMap.put("ursa", "小米8 透明探索版");
        deviceNameMap.put("ysl", "红米S2 / 红米Y2");
        deviceNameMap.put("wayne", "小米6X");
        deviceNameMap.put("polaris", "小米MIX 2S");
        deviceNameMap.put("whyred", "红米Note 5 / Pro");
        deviceNameMap.put("rosy", "红米5");
        deviceNameMap.put("vince", "红米5 Plus");
        deviceNameMap.put("riva", "红米5A");
        deviceNameMap.put("chiron", "小米MIX 2");
        deviceNameMap.put("jason", "小米Note 3");
        deviceNameMap.put("tissot", "小米A1");
        deviceNameMap.put("ugg", "红米Note 5A 高配版");
        deviceNameMap.put("ugglite", "红米Note 5A 标准版");
        deviceNameMap.put("tiffany", "小米5X");
        deviceNameMap.put("oxygen", "小米Max 2");
        deviceNameMap.put("sagit", "小米6");
        deviceNameMap.put("cappu", "小米平板3");
        deviceNameMap.put("meri", "小米5C");
        deviceNameMap.put("santoni", "红米4X");
        deviceNameMap.put("mido", "红米Note 4X 高通版");
        deviceNameMap.put("nikel", "红米Note 4 联发科版");
        deviceNameMap.put("markw", "红米4 高配版");
        deviceNameMap.put("prada", "红米4 标准版");
        deviceNameMap.put("rolex", "红米4A");
        deviceNameMap.put("lithium", "小米MIX");
        deviceNameMap.put("scorpio", "小米Note 2");
        deviceNameMap.put("capricorn", "小米5S");
        deviceNameMap.put("natrium", "小米5S Plus");
        deviceNameMap.put("omega", "红米Pro");
        deviceNameMap.put("land", "红米3S");
        deviceNameMap.put("helium", "小米Max 高配版");
        deviceNameMap.put("hydrogen", "小米Max 标准版");
        deviceNameMap.put("aqua", "小米4S");
        deviceNameMap.put("gemini", "小米5");
        deviceNameMap.put("ido", "红米3 / Pro");
        deviceNameMap.put("kate", "红米Note 3 台湾特别版");
        deviceNameMap.put("kenzo", "红米Note 3 全网通版");
        deviceNameMap.put("hennessy", "红米Note 3 双网通版");
        deviceNameMap.put("latte", "小米平板2");
        deviceNameMap.put("libra", "小米4C");
        deviceNameMap.put("hermes", "红米Note 2");
        deviceNameMap.put("ferrari", "小米4i");
        deviceNameMap.put("lte26007", "红米2A 标准版");
        deviceNameMap.put("leo", "小米Note 顶配版");
        deviceNameMap.put("virgo", "小米Note 双网通 / 全网通");
        deviceNameMap.put("wt86047", "红米手机2 增强版");
        deviceNameMap.put("wt88047", "红米手机2");
        deviceNameMap.put("dior", "红米Note 4G单卡版");
        deviceNameMap.put("gucci", "红米Note 4G双卡版");
        deviceNameMap.put("cancro", "小米3 / 小米4");
        deviceNameMap.put("armani", "红米手机1S");
        deviceNameMap.put("HM2014011", "红米手机1S 移动3G版");
        deviceNameMap.put("HM2014501", "红米手机1S 移动4G版");
        deviceNameMap.put("mocha", "小米平板1");
        deviceNameMap.put("lcsh92", "红米Note");
        deviceNameMap.put("taurus", "小米2A");
        deviceNameMap.put("pisces", "小米3 移动版");
        deviceNameMap.put("HM2013023", "红米手机");
        deviceNameMap.put("aries", "小米2S");
        deviceNameMap.put("mione", "小米1S");
    }

    public static String getDeviceName(String deviceCode) {
        // 查找设备代号对应的设备名称，如果找不到则返回原始的设备代号
        return deviceNameMap.getOrDefault(deviceCode, deviceCode);
    }
}
